main: us.fihgu.minigamecore.Loader
name: MinigameCore
version: 1.0
author: fihgu
depend: [Toolbox]
description: Core plugin that other minigame uses.
commands:
 menu:
  description: shows the main menu.
  usage: /menu